name: CSV conversion
 
on:
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab
 
jobs:
  fetch-results:
    runs-on: ubuntu-latest
    permissions: 
        contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
           pip install requests
           python -m pip install --upgrade pip
           pip install pandas
                  
      - name: Run script to csv conversion
        run: python main.py
        
      - name: Commit and push csv file
        run: |
          git config --global user.name 'Gee-tha-S'
          git config --global user.email 'github-actions[bot]@users.geethasrinivasan2000@gmail.com'
          git add code-scanning.csv
          git commit -m 'Add generated code-scanning-alerts.csv'
          git push
        env:
          TOKEN: ${{ secrets.TOKEN}}
      
